[package]
name = "wormhole-token-bridge-solana"
description = "Wormhole Token Bridge Program for Solana"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
#name = "core_bridge_program"

[features]
default = ["mainnet", "cpi", "no-idl"]
### A.K.A. Local Validator (via JS Integration Test) and Tilt
localnet = ["core-bridge-program/localnet"]
### A.K.A. Solana Mainnet-Beta
mainnet = ["core-bridge-program/mainnet"]
### A.K.A. Solana Devnet
testnet = ["core-bridge-program/testnet"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]

[dependencies.core-bridge-program]
path = "../core-bridge"
version = "0.0.1-alpha.3"
package = "wormhole-core-bridge-solana"
features = ["cpi"]
default-features = false

[dependencies]
anchor-spl = { workspace = true, features = ["metadata"] }
mpl-token-metadata = { version = "1.13.2", features = ["no-entrypoint"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

wormhole-raw-vaas.workspace = true

anchor-lang.workspace = true
solana-program.workspace = true

hex.workspace = true
ruint.workspace = true

cfg-if.workspace = true

[dev-dependencies]
hex-literal.workspace = true